### ISSUE TITLE
Model Summaries

### ISSUE THREAD

**Issue by brandonwillard** [TaddyLab/gamlr#7]
Is it possible to get per-model summaries (as with `lm`)?
Also, it would be awesome to have output amenable to [`broom`](https://github.com/hadley/broom).

**Comment by mataddy** [comment]
`
summary(fit)
`
since we fit regularization paths, this contains a very different set of info from what lm produces (or what hadley envisions with broom, I thik).

Also, the full path of coefficients is
`
coef(fit, select=0)
`
is, along with fit$lambda, basically all there is to about the fitted model.  a cv.gamlr object has the OOS experiment, for which you can do summary(cv.fit) of course.
